; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Lego Rock Raiders"
#define MyAppPublisher "Research Realm"
#define MyAppURL "https://researchrealm.net/"
#define MyAppExeName "LegoRR.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{35950306-3CBE-44A4-BE06-CB30D03BAF53}
AppName={#MyAppName}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; We put everything except Baz's Mod into the same folder, so the language of choice is reused when modding/using OpenLRR
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename={#MyAppName} Slovenian installer
SolidCompression=yes
; Fixes out of memory when compiling with multiple Threads
LZMAUseSeparateProcess=yes
; If you can't compile b/c of high CPU usage, just turn this one down to like 4 or lower
LZMANumBlockThreads=16
; lzma2/max is the default, the one below is two steps stronger (strongest) with higher memory requirement.
Compression=lzma2/ultra64
; These two compress it even more, if you have difficulties with compiling comment these first!
LZMADictionarySize=1048576
LZMANumFastBytes=273
; Ignore admin system wide install but using current user hkey location. See comment at Registry
UsedUserAreasWarning=no
WizardStyle=classic
; Installer Graphics
SetupIconFile=/resources/images/RR_Logo_Mockup_B.ico
WizardImageFile=/resources/images/SidebarRR.bmp
WizardSmallImageFile=/resources/images/Image-Small.bmp
WizardImageStretch=True

[Messages]
ReadyLabel2b=This custom installer is a hobby project brought to you by the members of the wiki research realm project. This is NOT an official LEGO release and NO donations are accepted and NEVER will be! By clicking install you'll agree to having read the above text.

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\LANGS\si\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\LANGS\si\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
;Registry data from file lrr.reg
; I manually added this one, this basically makes the game work in windowed but also fix the TNT bug and ingame cutscene's. The HKCU location is not something you should set because it's user specific and we're doing a system wide install. But it's not an issue but gives a warning in the compiler.
Root: HKCU; Subkey: "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; ValueType: string; ValueName: "C:\Program Files (x86)\{#MyAppName}\{#MyAppExeName}"; ValueData: "~ 16BITCOLOR WINXPSP3 DWM8And16BitMitigation"; Flags: uninsdeletevalue
;End of registry data from file lrr.reg
;SOME KEYS FILTERED DUE TO PRIVILEGESREQUIRED SETTINGS!
;Because of the above, had to manually get those lines above here, so try to reuse this file

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "-best"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "-best"
